source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]


group :development do
  gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'
  gem 'pry-rails', '~> 0.3.11'
end

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem 'pry', '~> 0.16.0'
  gem 'pry-byebug', '~> 3.12'
end
